# Generated by Django 6.1.1 on 2026-09-17 06:54

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Device',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('tb_device_id', models.UUIDField(help_text='ThingsBoard device UUID', unique=True)),
                ('name', models.CharField(max_length=120)),
                ('mac_address', models.CharField(blank=True, max_length=17)),
                ('location_name', models.CharField(blank=True, max_length=200)),
                ('location_x', models.FloatField(default=0.5, help_text='0.0–1.0 for SVG floorplan')),
                ('location_y', models.FloatField(default=0.5)),
                ('firmware_version', models.CharField(blank=True, max_length=50)),
                ('tb_access_token', models.CharField(blank=True, help_text='ThingsBoard device access token', max_length=255)),
                ('current_risk_level', models.CharField(choices=[('NORMAL', 'Normal'), ('LOW', 'Low'), ('MEDIUM', 'Medium'), ('HIGH', 'High'), ('CRITICAL', 'Critical')], default='NORMAL', max_length=10)),
                ('current_risk_score', models.FloatField(default=0.0)),
                ('added_at', models.DateTimeField(auto_now_add=True)),
                ('notes', models.TextField(blank=True)),
                ('organization', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='devices', to='accounts.organization')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
    ]
