# Generated by Django 6.1.1 on 2026-09-17 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devices', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='device',
            name='weather_location',
            field=models.CharField(blank=True, help_text='City name for the weather widget', max_length=100, null=True),
        ),
    ]
