version: '3.8'

services:
  web:
    build: .
    command: gunicorn --bind 0.0.0.0:8000 config.wsgi:application
    volumes:
      - ./web:/app
    ports:
      - "8000:8000"
    env_file:
      - ./web/.env
    depends_on:
      - redis
  
  celery_worker:
    build: .
    command: celery -A config worker -l info
    volumes:
      - ./web:/app
    env_file:
      - ./web/.env
    depends_on:
      - redis
      - web

  redis:
    image: redis:7-alpine

