version: '3.8'

services:
  web:
    build: .
    command: daphne -b 0.0.0.0 -p 8000 config.asgi:application
    volumes:
      - ./web:/app
    ports:
      - "8000:8000"
    extra_hosts:
      - "host.docker.internal:host-gateway"
    env_file:
      - ./web/.env
    depends_on:
      - redis
  
  celery_worker:
    build: .
    command: celery -A config worker -l info
    volumes:
      - ./web:/app
    extra_hosts:
      - "host.docker.internal:host-gateway"
    env_file:
      - ./web/.env
    depends_on:
      - redis
      - web

  redis:
    image: redis:7-alpine

