# Generated by Django 6.1.1 on 2026-09-17 13:14

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alarms', '0002_alarm_cancellation_deadline_and_more'),
        ('notifications', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmergencyContact',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=150)),
                ('organization', models.CharField(blank=True, max_length=150)),
                ('channel', models.CharField(choices=[('EMAIL', 'Email'), ('TELEGRAM', 'Telegram')], max_length=20)),
                ('target_address', models.CharField(max_length=255)),
                ('priority', models.IntegerField(default=1)),
                ('is_active', models.BooleanField(default=True)),
                ('is_verified', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='NotificationLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('SENT', 'Sent'), ('DELIVERED', 'Delivered'), ('FAILED', 'Failed'), ('ACKNOWLEDGED', 'Acknowledged')], default='PENDING', max_length=20)),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
                ('error_message', models.TextField(blank=True)),
                ('alarm', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='alarms.alarm')),
                ('contact', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='notifications.emergencycontact')),
            ],
        ),
    ]
