# Generated by Django 6.1.1 on 2026-09-17 15:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SystemSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('weather_location', models.CharField(default='New York', help_text='City name for the weather widget', max_length=100)),
            ],
            options={
                'verbose_name_plural': 'System Settings',
            },
        ),
    ]
