# Generated by Django 6.1.1 on 2026-09-17 06:54

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('devices', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AIModelVersion',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('version_tag', models.CharField(max_length=50, unique=True)),
                ('model_file', models.FileField(blank=True, null=True, upload_to='ai_models/')),
                ('training_samples', models.IntegerField(default=0)),
                ('feature_list', models.JSONField(default=list)),
                ('trained_at', models.DateTimeField(auto_now_add=True)),
                ('is_active', models.BooleanField(default=False)),
                ('notes', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='RiskAssessment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('ts', models.DateTimeField()),
                ('risk_score', models.FloatField()),
                ('risk_level', models.CharField(choices=[('LOW', 'Low'), ('MEDIUM', 'Medium'), ('HIGH', 'High'), ('CRITICAL', 'Critical')], max_length=10)),
                ('confidence', models.FloatField()),
                ('alarm_triggered', models.BooleanField(default=False)),
                ('feature_snapshot', models.JSONField(default=dict)),
                ('shap_values', models.JSONField(blank=True, default=dict, null=True)),
                ('device', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assessments', to='devices.device')),
                ('model_version', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='ai_engine.aimodelversion')),
            ],
        ),
    ]
