# Generated by Django 6.1.1 on 2026-09-17 13:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai_engine', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='riskassessment',
            name='alarm_reason',
            field=models.TextField(blank=True, help_text='AI-Generated reason for the alarm'),
        ),
    ]
