# Generated by Django 6.1.1 on 2026-09-17 13:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alarms', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='alarm',
            name='cancellation_deadline',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='alarm',
            name='cancellation_reason',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='alarm',
            name='cancelled_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cancelled_alarms', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='alarm',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pending Cancellation (10s)'), ('CANCELLED', 'Cancelled'), ('ESCALATING', 'Escalating'), ('EMERGENCY_NOTIFIED', 'Emergency Notified'), ('ACKNOWLEDGED', 'Acknowledged'), ('RESOLVED', 'Resolved'), ('FALSE_ALARM', 'False Alarm')], default='PENDING', max_length=20),
        ),
    ]
