# Generated by Django 6.1.1 on 2026-09-17 06:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SensorParameter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=100, unique=True)),
                ('display_name', models.CharField(max_length=100)),
                ('data_type', models.CharField(choices=[('BOOLEAN', 'Boolean'), ('NUMERIC', 'Numeric'), ('STRING', 'String')], default='NUMERIC', max_length=20)),
                ('unit', models.CharField(blank=True, max_length=20)),
                ('visualization', models.CharField(choices=[('AUTO', 'Auto-detect'), ('GAUGE', 'Gauge (0-100 or min/max)'), ('GRAPH_3AXIS', '3-Axis Graph (x/y/z)'), ('GRAPH', 'Line Graph'), ('STATUS', 'Status Indicator (ON/OFF)'), ('BATTERY', 'Battery Level'), ('BAR', 'Bar Meter')], default='AUTO', max_length=20)),
                ('danger_condition', models.CharField(blank=True, help_text="e.g. 'value > 2.0'", max_length=255)),
                ('include_in_ai', models.BooleanField(default=True)),
                ('active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
